import {
  CalenderIcon,
  CooperationIcon,
  CopyIcon,
  DegreeHatIcon,
  EditIcon,
  GlobalUserIcon,
  HeadphoneIcon,
  HosseinIcon,
  MeditationIcon,
  MusicIcon,
  SmileHeartIcon,
  UserHeadphoneIcon,
} from "@/share/components/base/icons";
import { MessageLockIcon } from "@/share/components/base/icons/message-lock";

export const menus = [
  {
    id: 1,
    label: "services",
    children: [
      {
        id: 11,
        label: "courses",
        icon: DegreeHatIcon,
        href: "/my-courses/courses",
        show: true,
        disabled: false,
      },
      {
        id: 12,
        label: "albums",
        icon: MusicIcon,
        href: "/my-courses/albums",
        show: true,
        disabled: false,
      },
      {
        id: 13,
        label: "live_meeting",
        icon: GlobalUserIcon,
        href: "/my-courses/live-meeting",
        show: true,
        disabled: false,
      },
    ],
  },
  {
    id: 2,
    label: "experience",
    children: [
      {
        id: 21,
        label: "podcast",
        icon: UserHeadphoneIcon,
        href: "/experience/podcast",
        show: true,
        disabled: false,
      },
      {
        id: 32,
        label: "meditation",
        icon: MeditationIcon,
        href: "/experience/meditation",
        show: true,
        disabled: false,
      },
      {
        id: 23,
        label: "reading",
        icon: CopyIcon,
        href: "/experience/reading",
        show: true,
        disabled: false,
      },
      {
        id: 24,
        label: "listening",
        icon: HeadphoneIcon,
        href: "/experience/listening",
        show: true,
        disabled: false,
      },
      {
        id: 25,
        label: "writing",
        icon: EditIcon,
        href: "/experience/writing",
        show: true,
        disabled: false,
      },
    ],
  },
  {
    id: 3,
    label: "",
    children: [
      {
        id: 31,
        label: "private_consultation",
        icon: MessageLockIcon,
        href: "/private-consultation",
        show: true,
        disabled: false,
      },
    ],
  },
  {
    id: 4,
    label: "",
    children: [
      {
        id: 41,
        label: "events",
        icon: CalenderIcon,
        href: "/my-courses/events",
        show: true,
        disabled: false,
      },
      {
        id: 42,
        label: "donation",
        icon: SmileHeartIcon,
        href: "/donation",
        show: true,
        disabled: false,
      },
      {
        id: 43,
        label: "about_us",
        icon: HosseinIcon,
        href: "/about-us",
        show: true,
        disabled: false,
      },
      {
        id: 44,
        label: "cooperation",
        icon: CooperationIcon,
        href: "/cooperation",
        show: true,
        disabled: false,
      },
    ],
  },
];
