import {
  CalenderIcon,
  CooperationIcon,
  CopyIcon,
  DegreeHatIcon,
  EditIcon,
  GlobalUserIcon,
  HeadphoneIcon,
  HosseinIcon,
  MeditationIcon,
  MessageLockIcon,
  MusicIcon,
  SmileHeartIcon,
  UserHeadphoneIcon,
} from '@/components/icons';

export const menus = [
  {
    children: [
      {
        disabled: false,
        href: '/my-courses/courses',
        icon: DegreeHatIcon,
        id: 11,
        label: 'courses',
        show: true,
      },
      {
        disabled: false,
        href: '/my-courses/albums',
        icon: MusicIcon,
        id: 12,
        label: 'albums',
        show: true,
      },
      {
        disabled: false,
        href: '/my-courses/live-meeting',
        icon: GlobalUserIcon,
        id: 13,
        label: 'live_meeting',
        show: true,
      },
    ],
    id: 1,
    label: 'services',
  },
  {
    children: [
      {
        disabled: false,
        href: '/experience/podcast',
        icon: UserHeadphoneIcon,
        id: 21,
        label: 'podcast',
        show: true,
      },
      {
        disabled: false,
        href: '/experience/meditation',
        icon: MeditationIcon,
        id: 32,
        label: 'meditation',
        show: true,
      },
      {
        disabled: false,
        href: '/experience/reading',
        icon: CopyIcon,
        id: 23,
        label: 'reading',
        show: true,
      },
      {
        disabled: false,
        href: '/experience/listening',
        icon: HeadphoneIcon,
        id: 24,
        label: 'listening',
        show: true,
      },
      {
        disabled: false,
        href: '/experience/writing',
        icon: EditIcon,
        id: 25,
        label: 'writing',
        show: true,
      },
    ],
    id: 2,
    label: 'experience',
  },
  {
    children: [
      {
        disabled: false,
        href: '/private-consultation',
        icon: MessageLockIcon,
        id: 31,
        label: 'private_consultation',
        show: true,
      },
    ],
    id: 3,
    label: '',
  },
  {
    children: [
      {
        disabled: false,
        href: '/my-courses/events',
        icon: CalenderIcon,
        id: 41,
        label: 'events',
        show: true,
      },
      {
        disabled: false,
        href: '/donation',
        icon: SmileHeartIcon,
        id: 42,
        label: 'donation',
        show: true,
      },
      {
        disabled: false,
        href: '/about-us',
        icon: HosseinIcon,
        id: 43,
        label: 'about_us',
        show: true,
      },
      {
        disabled: false,
        href: '/cooperation',
        icon: CooperationIcon,
        id: 44,
        label: 'cooperation',
        show: true,
      },
    ],
    id: 4,
    label: '',
  },
];
