export const courses = [
  {
    id: 99,
    package: 0,
    title_fa: "آناتومی انرژی",
    priority: 6,
    short_info:
      'دریافت درکِ کامل و جامع از "بدن انرژی" و نقش آن در سلامت "بدن فیزیکی"',
    full_info:
      '<p><span style="background-color: transparent; color: rgb(0, 0, 0);">گرچه "بدنِ انرژی" با چشم دیده نمیشود اما درست به اندازه "بدنِ فیزیکی" واقعی و حقیقیست. تمام آنچه در سطح ضمخت ماده و فیزیک در بدن تجربه میشود نتیجه اتفاقاتیست که در سطح لطیف تر انرژی در بدن رخ داده است. برای تعادل، تکامل، و سلامت فیزیکی و روانی آگاهی از ابعاد نهفته بدن یک ضرورت است و این دقیقا دلیل من برای نوشتن و گردهم آوری ورکشاپ : آناتومی انرژی" است. </span></p><p><span style="color: rgb(75, 86, 117);">&lt;v&gt; </span>انرژی ها در گردش هستند و من با کاِئنات هماهنگم .</p><p><br></p>',
    points: 5,
    show: 1,
    show_fa: 1,
    price: 15000000,
    discount_type: 1,
    discount_price: 15000000,
    discount_percent: null,
    capacity: 50000000,
    remain_capacity: 49987301,
    included_courses: [],
    included_courses_count: 0,
    count_chapters: 10,
    image_media: [
      {
        id: 257,
        course_id: 99,
        src: "https://admin.innoghte.ir/storage//app/public/front/images/courses/media/99/original/08b24785-8d9a-4e0a-9f26-4c2fd8ee0591.jpg",
      },
    ],
  },
  {
    id: 4,
    package: 0,
    title_fa: "تو از نو",
    priority: 4,
    short_info: "دوره جامع ترک عادات",
    full_info:
      '<p>رهایی از بند وابستگی، افزایش قدرت اراده و یافتن عظمت درون</p><p><span style="color: rgb(146, 146, 159);">&lt;v&gt;می تونی زندگی را با معجزه هایش تجربه کنی، وقتی "تو" خودت را "از نو" بسازی... </span></p>',
    points: 5,
    show: 1,
    show_fa: 1,
    price: 4000000,
    discount_type: 1,
    discount_price: 4000000,
    discount_percent: null,
    capacity: 2000000000,
    remain_capacity: 1999994659,
    included_courses: [],
    included_courses_count: 0,
    count_chapters: 12,
    image_media: [
      {
        id: 4,
        course_id: 4,
        src: "https://admin.innoghte.ir/storage/front/images/course_images/1723634786-hfYV7R28.jpg",
      },
    ],
  },
  {
    id: 3,
    package: 0,
    title_fa: "عبور از ترس",
    priority: 3,
    short_info:
      '"عبور از ترس"  یک تجربه منحصر به فرد برای ارتقاء سطح اعتماد به نفس و غلبه بر ترس و شک می باشد',
    full_info:
      "<p>همه ما در زندگـــی دچــار ترس و نــگرانی و شــک شــده ایــم.احســاس ناتـــوانی و شکســت را بارها و بارها تجــربه کرده ایم.</p><p>&lt;v&gt;این دوره یک تجربه منحصر به فرد برای ارتقاء سطح اعتماد به نفس و غلبه بر ترس و شک می باشد.</p><p><br></p>",
    points: 5,
    show: 1,
    show_fa: 1,
    price: 2590000,
    discount_type: 1,
    discount_price: 2590000,
    discount_percent: null,
    capacity: 2000000000,
    remain_capacity: 1999991026,
    included_courses: [],
    included_courses_count: 0,
    count_chapters: 10,
    image_media: [
      {
        id: 3,
        course_id: 3,
        src: "https://admin.innoghte.ir/storage/front/images/course_images/1723635109-5Ya7V8qd.jpg",
      },
    ],
  },
  {
    id: 2,
    package: 0,
    title_fa: "شروع بیداری",
    priority: 2,
    short_info:
      'دوره "شروع بیداری" اولین دوره جامع آموزش تن آرامی (مدیتیشن) به زبان فارسی است.',
    full_info:
      '<p>“شروع بیداری” اولین دوره مدیتیشن،</p><p>برای تو که تصمیم داری تمرین مدیتیشن را عمیق تر دنبال کنی</p><p>&lt;v&gt;دوره "شروع بیداری" از اولین گام کمکت می کنه که درون شگفت انگیز خودت را کشف کنی.</p>',
    points: 5,
    show: 1,
    show_fa: 1,
    price: 900000,
    discount_type: 1,
    discount_price: 900000,
    discount_percent: null,
    capacity: 2000000000,
    remain_capacity: 1999951617,
    included_courses: [],
    included_courses_count: 0,
    count_chapters: 8,
    image_media: [
      {
        id: 2,
        course_id: 2,
        src: "https://admin.innoghte.ir/storage/front/images/course_images/1723632939-xG9BcbgG.jpg",
      },
    ],
  },
  {
    id: 1,
    package: 0,
    title_fa: "عشق به خود",
    priority: 1,
    short_info:
      "“مهمترین ارتباطی که تا آخر عمر خواهی داشت، ارتباط بین تو و خودته!”",
    full_info:
      '<p class="ql-align-justify">"مهمترین ارتباطی که تا آخر عمر خواهی داشت، ارتباط بین تو و خودته! "و کیفیت این ارتباط تعیین کننده کیفیت سایر جوانب زندگیته و تو این ورکشاب دقیقا روی ارتقاء و بهبود همین ارتباط تمرکز می کنیم و با استفاده از روش های به روز روانشناسی و Neuroscience مثل EFT، ژورنالینگ، مدیتیشن، پرانایاما به اصالت، به صمیمیت و به عشقی که حق طبیعی ماست برمیگردیم و نسخه متفاوتی از خودمون رو تجربه خواهیم کرد. تو این نسخه جدید دنیا رو خونه خودمون میدونیم. با احساس امنیت و آرامش زندگی رو زندگی می کنیم. با خودمون آشتی هستیم و از خودمون ایراد نمی گیریم. جایگاه و هویت اصیل گم شده خودمون رو پیدا می کنیم و از عمق وجود متوجه ارزش و اهمیت خودمون میشیم. اعتماد به نفس بیشتری داریم و مدام برای جلب رضایت اطرافیان خودمون رو زیر پا نمیزاریم.<span style="color: rgb(146, 146, 159);">&lt;v&gt;</span>کسی که خودش رو کاملاً دوست داره، کنترل مستقیم سرنوشت خود را هم تو دستاش داره...</p><p class="ql-align-justify"><br></p><p><br></p>',
    points: 4.99,
    show: 1,
    show_fa: 1,
    price: 7000000,
    discount_type: 1,
    discount_price: 7000000,
    discount_percent: null,
    capacity: 2000000000,
    remain_capacity: 1999976587,
    included_courses: [],
    included_courses_count: 0,
    count_chapters: 10,
    image_media: [
      {
        id: 1,
        course_id: 1,
        src: "https://admin.innoghte.ir/storage/front/images/course_images/1723633252-MSnm6m0s.jpg",
      },
    ],
  },
];
